### ISSUE TITLE
it_should_behave_like -  Could not find shared examples "IceNine.deep_freeze"

### ISSUE THREAD

**Issue by hggh** [dkubb/ice_nine#15]
while building your gem for Debian, rake test fails:

```
ecursion_guard/frozen/guard_spec.rb ./spec/unit/ice_nine/recursion_guard/object_set/guard_spec.rb ./spec/unit/object/deep_freeze_spec.rb
/usr/lib/ruby/vendor_ruby/rspec/core/example_group.rb:168:in `find_and_eval_shared': Could not find shared examples "IceNine.deep_freeze" (ArgumentError)
    from /usr/lib/ruby/vendor_ruby/rspec/core/example_group.rb:120:in `block in it_should_behave_like'
    from /usr/lib/ruby/vendor_ruby/rspec/core/example_group.rb:246:in `module_eval'
    from /usr/lib/ruby/vendor_ruby/rspec/core/example_group.rb:246:in `subclass'
    from /usr/lib/ruby/vendor_ruby/rspec/core/example_group.rb:232:in `describe'
    from /usr/lib/ruby/vendor_ruby/rspec/core/example_group.rb:119:in `it_should_behave_like'
    from /home/jonas/debian/ruby-ice-nine/spec/integration/ice_nine/class_methods/deep_freeze_bang_spec.rb:20:in `block in <top (required)>'
    from /usr/lib/ruby/vendor_ruby/rspec/core/example_group.rb:246:in `module_eval'
    from /usr/lib/ruby/vendor_ruby/rspec/core/example_group.rb:246:in `subclass'
    from /usr/lib/ruby/vendor_ruby/rspec/core/example_group.rb:232:in `describe'
    from /usr/lib/ruby/vendor_ruby/rspec/core/dsl.rb:18:in `describe'
    from /home/jonas/debian/ruby-ice-nine/spec/integration/ice_nine/class_methods/deep_freeze_bang_spec.rb:7:in `<top (required)>'
    from /usr/lib/ruby/vendor_ruby/rspec/core/configuration.rb:896:in `load'
    from /usr/lib/ruby/vendor_ruby/rspec/core/configuration.rb:896:in `block in load_spec_files'
    from /usr/lib/ruby/vendor_ruby/rspec/core/configuration.rb:896:in `each'
    from /usr/lib/ruby/vendor_ruby/rspec/core/configuration.rb:896:in `load_spec_files'
    from /usr/lib/ruby/vendor_ruby/rspec/core/command_line.rb:22:in `run'
    from /usr/lib/ruby/vendor_ruby/rspec/core/runner.rb:80:in `run'
    from /usr/lib/ruby/vendor_ruby/rspec/core/runner.rb:17:in `block in autorun'
```

We have removed the it_should_behave_like call from the specs.

**Comment by boutil** [comment]
Hi!

It seems that requiring explicitly the shared examples in spec/spec_helper.rb, as recommended in the RSpec documentation helps. See point 2. in Conventions paragraph of:
https://relishapp.com/rspec/rspec-core/docs/example-groups/shared-examples.

**Comment by boutil** [comment]
```
--- a/spec/spec_helper.rb
+++ b/spec/spec_helper.rb
@@ -20,6 +20,8 @@
   end
 end
 
+Dir.glob("spec/shared/**/*.rb").each { |f| require f }
+
 require 'ice_nine'
 
 RSpec.configure do |config|
```
